feat: 🎸 catch truncate errors like "Must have child node"
DiZhou92/ngx-line-truncation pull request #32
Opened 2020-12-03 12:47 UTC by ThRintelen

2020-12-13 21:20 UTC, DiZhou92 requested changes

2020-12-13 21:20 UTC, DiZhou92 commented on projects/line-truncation-lib/src/lib/line-truncation.directive.ts
>    Directive,
✅ but can you disable the formatter and only make the diff for your change, thank you!

2020-12-14 07:33 UTC, ThRintelen commented on projects/line-truncation-lib/src/lib/line-truncation.directive.ts
>    Directive,
done

2020-12-16 23:26 UTC, DiZhou92 commented on projects/line-truncation-lib/src/lib/line-truncation.directive.ts
>    Directive,
thanks, will merge and release on this weekend

2020-12-23 02:36 UTC, DiZhou92 approved these changes

2020-12-23 02:36 UTC, merged